KL13NT/valbot

- package.json
- src/commands/index.ts
- src/commands/play.ts
- src/controllers/MusicController.ts
- src/controllers/ToxicityController.ts
- src/controllers/index.ts
- src/listeners/MessageListener.ts
- src/utils/object.ts
- src/utils/youtube.ts
- yarn.lock
This PR introduces a `MusicController` component with support for building a queue, moving around the queue, fetching meta from YouTube, and a number of other operations. It handles connecting to voice channels, binding to text channels, as well as disconnecting when idle.
> Feature: Music Playing

- src/controllers/MusicController.ts
> fix: stream validity before playing #29

- package.json
- src/commands/play.ts
- src/controllers/MusicController.ts
- src/utils/youtube.ts
- yarn.lock
This PR adds support for playing songs by searching for a `query`.
> Feature: play by query

- src/controllers/MusicController.ts
- src/utils/general.ts
> Bot skips videos too soon

- src/loaders/CommandsLoader.ts
- src/types/interfaces.ts
Signed-off-by: Nabil <nabil.tharwat@outlook.com>
> feat: command aliases

- src/commands/play.ts
- src/controllers/MusicController.ts
- src/messages.json
Signed-off-by: Nabil <nabil.tharwat@outlook.com>
> Feature: resume

- src/ValClient.ts
- src/commands/clear-queue.ts
- src/messages.json
> fix: clear empty queue

- src/commands/clear-queue.ts
> feat: stop alias

- src/ValClient.ts
- src/commands/presenceclear.ts
- src/commands/presenceset.ts
- src/controllers/MusicController.ts
- src/controllers/PresenceController.ts
- src/controllers/index.ts
- src/loaders/ControllersLoader.ts
- src/types/interfaces.ts
> Feature: Music Presence

- src/commands/index.ts
- src/commands/jump.ts
- src/controllers/MusicController.ts
- src/messages.json
> feat: jump command

- src/commands/index.ts
- src/commands/remove.ts
- src/controllers/MusicController.ts
- src/messages.json
> feat: remove command

- src/commands/index.ts
- src/commands/previous-now.ts
- src/messages.json
> feat: previous-now

- src/commands/jump.ts
Issue #81 
Modified the related line to 5 seconds instead of 15.
> Refactor: Jump command should have shorter cooldown

- .all-contributorsrc
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .husky/commit-msg
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- COPYING
- README.md
- package.json
> Better documentation

- src/commands/index.ts
- src/commands/move.ts
- src/controllers/MusicController.ts
- src/messages.json
> feat: move

- src/controllers/MusicController.ts
> Feature: song ids

- src/Entities/PlayBehavior.ts
- Spotify Singles.
- Spotify Albums.
- Spotify Playlists.
Closes #74
> Feature: Spotify support

- src/Entities/PlayBehavior.ts
> Feature: Youtube search

- src/commands/index.ts
- src/commands/playlist.ts
- src/controllers/MusicController.ts
- src/messages.json
- src/structures/UserError.ts
- src/types/interfaces.ts
- src/utils/general.ts
>  Feature: Save Queue (Named Playlist) #88 

- src/commands/previous-now.ts
- src/loaders/CommandsLoader.ts
#90 
deleted second alias "PrevNow" 
and Fixed the uppercase sensitivity for all commands and aliases
> fix: command uppercase sensitivity

- src/messages.json
- src/structures/Interaction.ts
Signed-off-by: Nabil Tharwat <nabil.tharwat@outlook.com>
> feat: command cooldown logic per-user

- src/commands/clear-queue.ts
- src/commands/index.ts
- src/commands/jump.ts
- src/commands/lyrics.ts
- src/commands/now-playing.ts
- src/commands/queue.ts
- src/commands/refresh.ts
- src/commands/remove.ts
- src/commands/skip.ts
- src/listeners/InteractionListener.ts
- src/structures/PaginatedEmbed.ts
- Converted the rest of the music commands to slash commands
- Replaced reactions with buttons for the paginated messages
> Refactor: music/commands and added pagination buttons

- src/controllers/MusicController.ts
> fix: unintended move behavior
